/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  async rewrites() {
    return [
      { source: "/api/match", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/match` },
      { source: "/api/stats", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/stats` },
      { source: "/api/reindex", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/reindex` },
      { source: "/api/feedback", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/feedback` },
      { source: "/api/metrics", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/metrics` },
      { source: "/api/health", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/health` },
      { source: "/api/track/:trackId/audio", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/track/:trackId/audio` },
      { source: "/api/track/:trackId/pitch", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/track/:trackId/pitch` },
      { source: "/api/track/:trackId", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/track/:trackId` },
      { source: "/api/tracks", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/tracks` },
      { source: "/api/pitch", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/pitch` },
      { source: "/api/share", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/share` },
      { source: "/api/share/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/share/:id` },
      { source: "/api/history", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/history` },
      { source: "/api/history/export", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/history/export` },
      { source: "/api/history/views", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/history/views` },
      { source: "/api/history/views/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/history/views/:id` },
      { source: "/api/history/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/history/:id` },
      { source: "/api/me", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/me` },
      { source: "/api/usage", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/usage` },
      { source: "/api/webhooks", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/webhooks` },
      { source: "/api/webhooks/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/webhooks/:id` },
      { source: "/api/webhooks/:id/deliveries", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/webhooks/:id/deliveries` },
      { source: "/api/webhooks/:id/test", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/webhooks/:id/test` },
      { source: "/api/webhooks/:id/rotate-secret", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/webhooks/:id/rotate-secret` },
      { source: "/api/webhooks/:id/pause", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/webhooks/:id/pause` },
      { source: "/api/webhooks/:id/resume", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/webhooks/:id/resume` },
      { source: "/api/webhooks/:id/deliveries/:dId/redeliver", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/webhooks/:id/deliveries/:dId/redeliver` },
      { source: "/api/activity", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/activity` },
      { source: "/api/collections", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/collections` },
      { source: "/api/collections/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/collections/:id` },
      { source: "/api/keys", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/keys` },
      { source: "/api/keys/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/keys/:id` },
      { source: "/api/ip-allowlist", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/ip-allowlist` },
      { source: "/api/ip-allowlist/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/ip-allowlist/:id` },
      { source: "/api/sessions", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/sessions` },
      { source: "/api/sessions/policy", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/sessions/policy` },
      { source: "/api/sessions/revoke-all", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/sessions/revoke-all` },
      { source: "/api/sessions/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/sessions/:id` },
      { source: "/api/mfa", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/mfa` },
      { source: "/api/mfa/status", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/mfa/status` },
      { source: "/api/mfa/enroll", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/mfa/enroll` },
      { source: "/api/mfa/verify", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/mfa/verify` },
      { source: "/api/members", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/members` },
      { source: "/api/members/invite", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/members/invite` },
      { source: "/api/members/accept", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/members/accept` },
      { source: "/api/members/:id/resend", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/members/:id/resend` },
      { source: "/api/members/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/members/:id` },
      { source: "/api/sso/config", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/sso/config` },
      { source: "/api/sso/providers", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/sso/providers` },
      { source: "/api/sso/discover", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/sso/discover` },
      { source: "/api/audit", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/audit` },
      { source: "/api/audit/export", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/audit/export` },
      { source: "/api/quotas", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/quotas` },
      { source: "/api/residency", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/residency` },
      { source: "/api/admin/scim/token", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/admin/scim/token` },
      { source: "/api/v1/privacy/export", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/v1/privacy/export` },
      { source: "/api/v1/privacy/workspace-export", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/v1/privacy/workspace-export` },
      { source: "/api/v1/privacy/me", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/v1/privacy/me` },
      // Stable v1 public API: forward everything under /api/v1/* to the
      // backend /v1/* surface. Integrators target this prefix from curl,
      // python, JS, etc. and we promise not to break paths under it.
      { source: "/api/v1/:path*", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/v1/:path*` },
    ];
  },
};
export default nextConfig;
