/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  async rewrites() {
    return [
      { source: "/api/match", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/match` },
      { source: "/api/stats", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/stats` },
      { source: "/api/reindex", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/reindex` },
      { source: "/api/feedback", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/feedback` },
      { source: "/api/metrics", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/metrics` },
      { source: "/api/health", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/health` },
      { source: "/api/track/:trackId/audio", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/track/:trackId/audio` },
      { source: "/api/track/:trackId/pitch", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/track/:trackId/pitch` },
      { source: "/api/track/:trackId", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/track/:trackId` },
      { source: "/api/tracks", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/tracks` },
      { source: "/api/pitch", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/pitch` },
      { source: "/api/share", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/share` },
      { source: "/api/share/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/share/:id` },
      { source: "/api/history", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/history` },
      { source: "/api/history/export", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/history/export` },
      { source: "/api/history/views", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/history/views` },
      { source: "/api/history/views/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/history/views/:id` },
      { source: "/api/history/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/history/:id` },
      { source: "/api/me", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/me` },
      { source: "/api/usage", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/usage` },
      { source: "/api/webhooks", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/webhooks` },
      { source: "/api/webhooks/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/webhooks/:id` },
      { source: "/api/webhooks/:id/deliveries", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/webhooks/:id/deliveries` },
      { source: "/api/webhooks/:id/test", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/webhooks/:id/test` },
      { source: "/api/webhooks/:id/rotate-secret", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/webhooks/:id/rotate-secret` },
      { source: "/api/webhooks/:id/pause", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/webhooks/:id/pause` },
      { source: "/api/webhooks/:id/resume", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/webhooks/:id/resume` },
      { source: "/api/webhooks/:id/deliveries/:dId/redeliver", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/webhooks/:id/deliveries/:dId/redeliver` },
      { source: "/api/activity", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/activity` },
      { source: "/api/collections", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/collections` },
      { source: "/api/collections/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/collections/:id` },
      { source: "/api/keys", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/keys` },
      { source: "/api/keys/policy", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/keys/policy` },
      { source: "/api/keys/revoke-all", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/keys/revoke-all` },
      { source: "/api/keys/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/keys/:id` },
      { source: "/api/keys/:id/rotate", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/keys/:id/rotate` },
      { source: "/api/keys/:id/ip-allowlist", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/keys/:id/ip-allowlist` },
      { source: "/api/ip-allowlist", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/ip-allowlist` },
      { source: "/api/ip-allowlist/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/ip-allowlist/:id` },
      { source: "/api/embed-origins", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/embed-origins` },
      { source: "/api/embed-origins/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/embed-origins/:id` },
      { source: "/api/security-contacts", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/security-contacts` },
      { source: "/api/security-contacts/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/security-contacts/:id` },
      { source: "/api/security-contacts/:id/primary", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/security-contacts/:id/primary` },
      { source: "/api/support-grants", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/support-grants` },
      { source: "/api/support-grants/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/support-grants/:id` },
      { source: "/api/support-grants/:id/revoke", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/support-grants/:id/revoke` },
      { source: "/api/invite-domains", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/invite-domains` },
      { source: "/api/scope-policy", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/scope-policy` },
      { source: "/api/webhook-policy", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/webhook-policy` },
      { source: "/api/webhook-delivery-rate", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/webhook-delivery-rate` },
      { source: "/api/invite-domains/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/invite-domains/:id` },
      { source: "/api/dpa", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/dpa` },
      { source: "/api/dpa/accept", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/dpa/accept` },
      { source: "/api/sessions", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/sessions` },
      { source: "/api/sessions/policy", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/sessions/policy` },
      { source: "/api/sessions/revoke-all", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/sessions/revoke-all` },
      { source: "/api/sessions/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/sessions/:id` },
      { source: "/api/mfa", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/mfa` },
      { source: "/api/mfa/status", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/mfa/status` },
      { source: "/api/mfa/enroll", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/mfa/enroll` },
      { source: "/api/mfa/verify", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/mfa/verify` },
      { source: "/api/mfa/lockout", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/mfa/lockout` },
      { source: "/api/mfa/session", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/mfa/session` },
      { source: "/api/admin/mfa/lockouts", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/admin/mfa/lockouts` },
      { source: "/api/admin/mfa/lockouts/unlock", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/admin/mfa/lockouts/unlock` },
      { source: "/api/members", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/members` },
      { source: "/api/members/invite", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/members/invite` },
      { source: "/api/members/accept", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/members/accept` },
      { source: "/api/members/:id/resend", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/members/:id/resend` },
      { source: "/api/members/:id", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/members/:id` },
      { source: "/api/sso/config", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/sso/config` },
      { source: "/api/sso/providers", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/sso/providers` },
      { source: "/api/sso/discover", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/sso/discover` },
      { source: "/api/audit", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/audit` },
      { source: "/api/audit/export", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/audit/export` },
      { source: "/api/audit-forwarding", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/audit-forwarding` },
      { source: "/api/audit-forwarding/enable", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/audit-forwarding/enable` },
      { source: "/api/audit-forwarding/disable", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/audit-forwarding/disable` },
      { source: "/api/audit-forwarding/test", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/audit-forwarding/test` },
      { source: "/api/audit-forwarding/deliveries", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/audit-forwarding/deliveries` },
      { source: "/api/audit-forwarding/replay", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/audit-forwarding/replay` },
      { source: "/api/quotas", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/quotas` },
      { source: "/api/budget", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/budget` },
      { source: "/api/residency", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/residency` },
      { source: "/api/workspace/seat-limit", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/workspace/seat-limit` },
      { source: "/api/legal-holds", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/legal-holds` },
      { source: "/api/workspace/closure", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/workspace/closure` },
      { source: "/api/workspace/closure/history", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/workspace/closure/history` },
      { source: "/api/workspace/closure/:id/cancel", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/workspace/closure/:id/cancel` },
      { source: "/api/legal-holds/status", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/legal-holds/status` },
      { source: "/api/legal-holds/:id/release", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/legal-holds/:id/release` },
      { source: "/api/retention", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/retention` },
      { source: "/api/retention/enforce", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/retention/enforce` },
      { source: "/api/admin/scim/token", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/admin/scim/token` },
      { source: "/api/v1/privacy/export", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/v1/privacy/export` },
      { source: "/api/v1/privacy/workspace-export", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/v1/privacy/workspace-export` },
      { source: "/api/v1/privacy/me", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/v1/privacy/me` },
      // Stable v1 public API: forward everything under /api/v1/* to the
      // backend /v1/* surface. Integrators target this prefix from curl,
      // python, JS, etc. and we promise not to break paths under it.
      { source: "/api/v1/:path*", destination: `${process.env.CLAWHUM_API_URL || "http://127.0.0.1:7451"}/v1/:path*` },
    ];
  },
};
export default nextConfig;
